home-work5
AGB1Q84/frontenfCourse pull request #2
Opened 2023-08-22 10:42 UTC by AGB1Q84

Lsn-5

2023-09-04 05:57 UTC, bayzena requested changes

2023-09-04 05:57 UTC, bayzena commented on Maksatova Benazir/JavaScript/LSN-3/home work/main.js
> +let cycle7 = { green: "зеленый", red: "красный", blue: "голубой" };
Observe tabs

2023-09-04 05:57 UTC, bayzena commented on Maksatova Benazir/JavaScript/LSN-3/home work/main.js
> +  if (cycle7.hasOwnProperty(key)) {
Why this check? Do you go through the keys of this object and check whether it is in the same object?

2023-09-04 05:57 UTC, bayzena commented on Maksatova Benazir/JavaScript/LSN-4/home work/script.js
> +console.log(result);
Where is result from?

2023-09-04 05:57 UTC, bayzena commented on Maksatova Benazir/JavaScript/LSN-5/home work/script.js
> +  a: { b: 3 },
Observe tabs

2023-09-04 05:57 UTC, bayzena commented on Maksatova Benazir/JavaScript/LSN-5/home work/script.js
> +  key9: 8,
key1: 0,
  key2: 1,
  key3: 2,
  key4: 3,
  key5: 4,
  key6: 5,
  key7: 6,
  key8: 7,
  key9: 8,
  
  
No need, you rewrite them
const user3={}

2023-09-11 07:52 UTC, AGB1Q84 commented
Домашняя работа

2023-09-11 07:52 UTC, merged